#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpenCV.SDKDemo.Resource", IsApplication=true)]

namespace OpenCV.SDKDemo
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int camera_id = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int show_fps = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int any = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int back = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int calibrate = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int calibration = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int cameraCalibration = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int cameraControl = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int cameraPreview = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int camera_calibration_java_surface_view = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int colorBlobDetection = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int color_blob_detection_activity_surface_view = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int comparison = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int faceDetection = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int fd_activity_surface_view = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int front = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int imageManipulations = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int image_manipulations_activity_surface_view = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int mixedProcessing = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int preview_mode = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int puzzle = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int surfaceView = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int tutorial2_activity_surface_view = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int tutorial3_activity_java_surface_view = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int undistortion = 2130903062;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040001
			public const int CameraPreview = 2130968577;
			
			// aapt resource value: 0x7F040000
			public const int camera_calibration_surface_view = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int color_blob_detection_surface_view = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int face_detect_surface_view = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int image_manipulations_surface_view = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Main = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int Puzzle = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int tutorial2_surface_view = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int tutorial3_surface_view = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int calibration = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F060000
			public const int lbpcascade_frontalface = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070001
			public const int action_calibrate = 2131165185;
			
			// aapt resource value: 0x7F070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7F070002
			public const int calibrating = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int calibration = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int calibration_successful = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int calibration_unsuccessful = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int comparison = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int more_samples = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int original = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int please_wait = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int preview_mode = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int undistorted = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int undistortion = 2131165196;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001 }
			public static int[] CameraBridgeViewBase = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_camera_id = 0;
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_show_fps = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
